---
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Sagemaker Studio - SageMaker Studio Domain

Parameters:
  DeploymentName:
    Description: A prefix for the stacks in this setup.
    Type: String

Mappings:
  # JupyterLabImageArn from https://docs.aws.amazon.com/sagemaker/latest/dg/studio-jl.html#studio-jl-set-cli
  RegionalSettings:
    eu-west-1:
      JupyterLabImageArn: arn:aws:sagemaker:eu-west-1:470317259841:image/jupyter-server-3
    eu-north-1:
      JupyterLabImageArn: arn:aws:sagemaker:eu-north-1:243637512696:image/jupyter-server-3

Resources:

  SageMakerToLivyOnEmrIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::ImportValue: !Sub ${DeploymentName}-infra-emr-MasterSecurityGroup
      IpProtocol: tcp
      FromPort: 8998
      ToPort: 8998
      SourceSecurityGroupId:
        Fn::ImportValue: !Sub ${DeploymentName}-infra-studio-StudioSecurityGroup

  StudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      AppNetworkAccessType: VpcOnly
      AuthMode: SSO
      DefaultUserSettings:
        ExecutionRole:
          Fn::ImportValue: !Sub ${DeploymentName}-infra-studio-ExecutionRoleArn
        SecurityGroups:
          - Fn::ImportValue: !Sub ${DeploymentName}-infra-studio-StudioSecurityGroup
        JupyterServerAppSettings:
          DefaultResourceSpec:
            InstanceType: system
            SageMakerImageArn: !FindInMap [RegionalSettings, !Ref AWS::Region, JupyterLabImageArn]
      DomainName: !Ref AWS::StackName
      SubnetIds:
        - !ImportValue infra-vpc-sn-nat-a
        - !ImportValue infra-vpc-sn-nat-b
      VpcId: !ImportValue infra-vpc-VpcId
      Tags:
        - { Key: Name, Value: !Ref AWS::StackName }
